### ISSUE TITLE
pprint support

### ISSUE THREAD

**Issue by MrMcSnail** [wwdok/Quick-Python-Print#3]
Thanks for an absolute lifesaving extension! 

It would be great if there was feature where you could create a pprint( ) output... 
Is this possible?

**Comment by wwdok** [comment]
Hi, @MrMcSnail , I am sorry for the late reply ! I just saw this issue yesterday.
I upgrade this extension to 0.3.0, now you can go to setting:
1. change the print function from `print` to `pprint`.
2. uncheck the `Enable formatted string`.
Like following :
![image](https://github.com/wwdok/Quick-Python-Print/assets/43233772/2d3f5233-dab4-417d-99f2-179353bdd428)

**Comment by nc-kyle-mcphail** [comment]
@wwdok I've only just seen your response to this issue. 

Thank you!! Amazing!!🎉
